name: delivery_app
description: "A new Flutter project."
version: 0.0.1+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Widgets
  flutter_svg: ^2.0.7
  pinput: ^4.0.0

  # Dependency injection
  flutter_riverpod: ^2.4.0

  # Navigation
  auto_route: ^7.8.4

  # Code generation
  auto_route_generator: ^7.3.2

  # Fonts
  google_fonts: ^6.1.0

  # Validation
  email_validator: ^2.1.17


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.3.1

  # Lints
  flutter_lints: ^2.0.0

flutter_gen:
  output: lib/src/core/resources
  line_length: 80

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        # Black
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        # Black
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        # Bold
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        # Bold Italic
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        # Medium
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        # Medium Italic
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        # Regular
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        # Light
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        # Light Italic
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        # Thin
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        # Thin Italic
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic




