name: delivery_app
description: "A new Flutter project."
version: 0.0.1+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Widgets
  flutter_svg: ^2.0.7
  pinput: ^4.0.0
  yandex_mapkit_lite: ^1.0.0

  # Dependency injection
  flutter_riverpod: ^2.4.0

  # Business logic
  flutter_bloc: ^8.1.4

  # Navigation
  auto_route: ^7.8.4

  # Code generation
  auto_route_generator: ^7.3.2
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1

  # Fonts
  google_fonts: ^6.1.0

  # Validation
  email_validator: ^2.1.17

  # Data base
  supabase_flutter: ^2.3.4
  shared_preferences: ^2.2.2

  # Network
  dio: ^5.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.3.1

  # Lints
  flutter_lints: ^2.0.0

flutter_gen:
  output: lib/src/core/resources
  line_length: 80

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/